### PR TITLE
Roles and authorization

### PR DESCRIPTION
**Pull request by vlki**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
❤️

**Comment by vlki** [comment]
In short
* There is a list of permissions https://github.com/Demagog2/demagog/pull/109/files#diff-7863dd934f73db4d813673b9dec6db0a
* Each role has defined set of permissions https://github.com/Demagog2/demagog/pull/109/files#diff-7863dd934f73db4d813673b9dec6db0aR53
* Each user has exactly one role now
* GraphQL mutations check relevant permissions
* Current user (the logged-in one) is now loaded into Redux state
* There is a new `<Authorize />` component which takes permissions and checks them against permissions of the current user, if user does not have the permissions children of that component are not rendered

**Comment by vaclavbohac** [comment]
@vlki Just a little note  – did you consider adding user information into the `bootstrap` query? It was meant exactly for these purposes.

**Comment by vlki** [comment]
Ah, good point, no. I did not realize we had bootstrap query. Will merge
current user into it at some point.

**Pull request merged**
