### PR TITLE
Removed .DS_Store files from repo

### PR DESCRIPTION
**Pull request by jan-martinek**
(Kinda glad I'm not the only one who commited one :))

### CODE REVIEW

**Comment by vaclavbohac** [comment]
@jan-martinek Apart from those files you removed, would you add new exclude rule to the `.gitignore` file?

**Comment by jan-martinek** [comment]
I believe almost nobody wants file like these in repos, so I think we'd better add this to our global ones.

**Comment by jan-martinek** [comment]
(I lost mine when migrating to my new computer last fall…)

**Comment by vaclavbohac** [comment]
Putting it to project's `.gitignore` is IMHO more defensive as it does not rely on ones personal settings

**Comment by jan-martinek** [comment]
I followed the advice from *the internets* on this, but of course, it's valid remark. Adding it.

**Pull request merged**
